In [ ]:
!pip install apyori

Collecting apyori
  Downloading apyori-1.1.2.tar.gz (8.6 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: apyori
  Building wheel for apyori (setup.py) ... done
  Created wheel for apyori: filename=apyori-1.1.2-py3-none-any.whl size=5955 sha256=e5a1e88538470a97cf617174c3442cbcb60c8dbdc46c45a7a8f84da8a97f2961
  Stored in directory: /root/.cache/pip/wheels/c4/1a/79/20f55c470a50bb3702a8cb7c94d8ada15573538c7f4baebe2d
Successfully built apyori
Installing collected packages: apyori
Successfully installed apyori-1.1.2

In [ ]:
import pandas as pd
import numpy as np
from apyori import apriori
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [ ]:
df = pd.read_csv('DATA.csv')

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [ ]:
df.head()

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
0,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
1,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
2,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
3,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
4,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K

RULE 1:\tfro
zenset({'Instant food products', 'hamburger meat'})\nSUPPORT:\t0.003050330452465684

If a customer buys "Instant food products" and "hamburger meat", then there is a support of 0.00305, which means that these items are purchased together in approximately 0.305% of all transactions.

In [ ]:
df.isnull().sum()

39                0
 State-gov        0
77516             0
 Bachelors        0
13                0
 Never-married    0
 Adm-clerical     0
 Not-in-family    0
 White            0
 Male             0
2174              0
0                 0
40                0
 United-States    0
 <=50K            0
dtype: int64

In [ ]:
df.columns

Index(['39', ' State-gov', '77516', ' Bachelors', '13', ' Never-married',
       ' Adm-clerical', ' Not-in-family', ' White', ' Male', '2174', '0', '40',
       ' United-States', ' <=50K'],
      dtype='object')

In [ ]:
#adding column names on each column
column_names = ["age", "workclass", "fnlwgt", "education", "education-num", "marital-status",
                "occupation", "relationship", "race", "sex", "capital-gain", "capital-loss",
                "hours-per-week", "native-country", "income"]
df = pd.read_csv('DATA.csv', names=column_names)

num_cols = df.select_dtypes(include=['int64', 'float64', 'int32']).columns
categorical_cols = ['workclass', 'education', 'marital-status', 'occupation',
                    'relationship', 'race', 'sex', 'native-country']

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [ ]:
df.head()

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [ ]:
#selecting only 500 rows instead of 32561
df = df.head(500)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [ ]:
df.head()

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             500 non-null    int64
 1   workclass       500 non-null    object
 2   fnlwgt          500 non-null    int64
 3   education       500 non-null    object
 4   education-num   500 non-null    int64
 5   marital-status  500 non-null    object
 6   occupation      500 non-null    object
 7   relationship    500 non-null    object
 8   race            500 non-null    object
 9   sex             500 non-null    object
 10  capital-gain    500 non-null    int64
 11  capital-loss    500 non-null    int64
 12  hours-per-week  500 non-null    int64
 13  native-country  500 non-null    object
 14  income          500 non-null    object
dtypes: int64(6), object(9)
memory usage: 58.7+ KB

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [ ]:
df.describe()

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,age,fnlwgt,education-num,capital-gain,capital-loss,hours-per-week
count,500.000000,5.000000e+02,500.000000,500.000000,500.000000,500.000000
mean,37.984000,1.956076e+05,10.076000,564.648000,107.898000,39.588000
std,13.449965,1.152173e+05,2.599951,2646.056895,440.092589,11.795445
min,17.000000,2.117400e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.165635e+05,9.000000,0.000000,0.000000,40.000000
50%,36.500000,1.839230e+05,10.000000,0.000000,0.000000,40.000000
75%,46.000000,2.503790e+05,12.000000,0.000000,0.000000,40.250000
max,90.000000,1.033222e+06,16.000000,34095.000000,2415.000000,98.000000

In [ ]:
records = []
num_cols = len(df.columns)

for i in range(len(df)):
    records.append([str(df.values[i, u]) for u in range(num_cols)])

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [ ]:
rules = apriori(records, min_support=0.0022, min_confidence=0.20, min_lift=3, min_length = 4)

results = list(rules)
results_list = []
for i in range(0, len(results)):
    results_list.append('RULE:\t' + str(results[i][0]) + '\nSUPPORT:\t' + str(results[i][1]))

print(len(results_list))
print(results_list)

In [ ]:
#applying one hot encoding
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()

encoded_data = encoder.fit_transform(df[categorical_cols]).toarray()
encoded_df = pd.DataFrame(encoded_data, columns=encoder.get_feature_names_out(categorical_cols))

binarized_df = pd.concat([encoded_df, df[num_cols]], axis=1)

print(binarized_df.head())

In [ ]:
#Seting support and confidence thresholds
min_support_values = [0.05, 0.1, 0.15]
min_confidence = 0.7

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [ ]:
#Converting all non-binary columns to binary
binarized_df = binarized_df.apply(lambda x: np.where(x > 0, 1, 0))

#Calculating frequent itemsets
for min_support in min_support_values:
    frequent_itemsets = apriori(binarized_df, min_support=min_support, use_colnames=True)
    rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=min_confidence)
    top_10_rules = rules.nlargest(10, "confidence")

    print(f"Rules for min_support={min_support:.2f}:")
    for i, (_, row) in enumerate(top_10_rules.iterrows(), start=1):
        antecedent = row['antecedents']
        consequent = row['consequents']
        confidence = row['confidence']

        print(f"Rule {i}: If {antecedent} then {consequent} (Confidence: {confidence:.2f})")

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/mlxtend/frequent_patterns/fpcommon.py:110: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

Rules for min_support=0.05:
Rule 1: If frozenset({'workclass_ ?'}) then frozenset({'occupation_ ?'}) (Confidence: 1.00)
Rule 2: If frozenset({'workclass_ ?'}) then frozenset({'age'}) (Confidence: 1.00)
Rule 3: If frozenset({'workclass_ ?'}) then frozenset({'fnlwgt'}) (Confidence: 1.00)
Rule 4: If frozenset({'workclass_ ?'}) then frozenset({'education-num'}) (Confidence: 1.00)
Rule 5: If frozenset({'workclass_ ?'}) then frozenset({'hours-per-week'}) (Confidence: 1.00)
Rule 6: If frozenset({'workclass_ Local-gov'}) then frozenset({'age'}) (Confidence: 1.00)
Rule 7: If frozenset({'workclass_ Local-gov'}) then frozenset({'fnlwgt'}) (Confidence: 1.00)
Rule 8: If frozenset({'workclass_ Local-gov'}) then frozenset({'education-num'}) (Confidence: 1.00)
Rule 9: If frozenset({'workclass_ Local-gov'}) then frozenset({'hours-per-week'}) (Confidence: 1.00)
Rule 10: If frozenset({'workclass_ Private'}) then frozenset({'age'}) (Confidence: 1.00)

/usr/local/lib/python3.10/dist-packages/mlxtend/frequent_patterns/fpcommon.py:110: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

Rules for min_support=0.10:
Rule 1: If frozenset({'workclass_ Private'}) then frozenset({'age'}) (Confidence: 1.00)
Rule 2: If frozenset({'workclass_ Private'}) then frozenset({'fnlwgt'}) (Confidence: 1.00)
Rule 3: If frozenset({'workclass_ Private'}) then frozenset({'education-num'}) (Confidence: 1.00)
Rule 4: If frozenset({'workclass_ Private'}) then frozenset({'hours-per-week'}) (Confidence: 1.00)
Rule 5: If frozenset({'education_ Bachelors'}) then frozenset({'age'}) (Confidence: 1.00)
Rule 6: If frozenset({'education_ Bachelors'}) then frozenset({'fnlwgt'}) (Confidence: 1.00)
Rule 7: If frozenset({'education_ Bachelors'}) then frozenset({'education-num'}) (Confidence: 1.00)
Rule 8: If frozenset({'education_ Bachelors'}) then frozenset({'hours-per-week'}) (Confidence: 1.00)
Rule 9: If frozenset({'education_ HS-grad'}) then frozenset({'age'}) (Confidence: 1.00)
Rule 10: If frozenset({'education_ HS-grad'}) then frozenset({'fnlwgt'}) (Confidence: 1.00)

/usr/local/lib/python3.10/dist-packages/mlxtend/frequent_patterns/fpcommon.py:110: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

Rules for min_support=0.15:
Rule 1: If frozenset({'workclass_ Private'}) then frozenset({'age'}) (Confidence: 1.00)
Rule 2: If frozenset({'workclass_ Private'}) then frozenset({'fnlwgt'}) (Confidence: 1.00)
Rule 3: If frozenset({'workclass_ Private'}) then frozenset({'education-num'}) (Confidence: 1.00)
Rule 4: If frozenset({'workclass_ Private'}) then frozenset({'hours-per-week'}) (Confidence: 1.00)
Rule 5: If frozenset({'education_ Bachelors'}) then frozenset({'age'}) (Confidence: 1.00)
Rule 6: If frozenset({'education_ Bachelors'}) then frozenset({'fnlwgt'}) (Confidence: 1.00)
Rule 7: If frozenset({'education_ Bachelors'}) then frozenset({'education-num'}) (Confidence: 1.00)
Rule 8: If frozenset({'education_ Bachelors'}) then frozenset({'hours-per-week'}) (Confidence: 1.00)
Rule 9: If frozenset({'education_ HS-grad'}) then frozenset({'age'}) (Confidence: 1.00)
Rule 10: If frozenset({'education_ HS-grad'}) then frozenset({'fnlwgt'}) (Confidence: 1.00)

In [ ]:
def calculate_interest(rule):
    return rule['confidence'] * rule['lift']

min_support_values = [0.05, 0.1, 0.15]
min_interest_values = [0.5, 0.7, 0.9]

for min_support in min_support_values:
    frequent_itemsets = apriori(binarized_df, min_support=min_support, use_colnames=True)

    for min_interest in min_interest_values:
        rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=min_confidence)
        #calculating interest measure for each rule
        rules['interest'] = rules.apply(calculate_interest, axis=1)

        #Ranking top 10 rules based on interest
        top_10_rules = rules.nlargest(10, "interest")

        print(f"Rules for min_support={min_support:.2f} and min_interest={min_interest:.2f}:")
        for i, (_, row) in enumerate(top_10_rules.iterrows(), start=1):
            antecedent = row['antecedents']
            consequent = row['consequents']
            confidence = row['confidence']
            lift = row['lift']
            interest = row['interest']

            print(f"Rule {i}: If {antecedent} then {consequent} (Confidence: {confidence:.2f}, Lift: {lift:.2f}, Interest: {interest:.2f})")

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/mlxtend/frequent_patterns/fpcommon.py:110: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

Rules for min_support=0.05 and min_interest=0.50:
Rule 1: If frozenset({'workclass_ ?'}) then frozenset({'occupation_ ?'}) (Confidence: 1.00, Lift: 17.67, Interest: 17.67)
Rule 2: If frozenset({'workclass_ ?', 'native-country_ United-States'}) then frozenset({'occupation_ ?'}) (Confidence: 1.00, Lift: 17.67, Interest: 17.67)
Rule 3: If frozenset({'workclass_ ?', 'age'}) then frozenset({'occupation_ ?'}) (Confidence: 1.00, Lift: 17.67, Interest: 17.67)
Rule 4: If frozenset({'workclass_ ?'}) then frozenset({'age', 'occupation_ ?'}) (Confidence: 1.00, Lift: 17.67, Interest: 17.67)
Rule 5: If frozenset({'workclass_ ?', 'fnlwgt'}) then frozenset({'occupation_ ?'}) (Confidence: 1.00, Lift: 17.67, Interest: 17.67)
Rule 6: If frozenset({'workclass_ ?'}) then frozenset({'occupation_ ?', 'fnlwgt'}) (Confidence: 1.00, Lift: 17.67, Interest: 17.67)
Rule 7: If frozenset({'workclass_ ?', 'education-num'}) then frozenset({'occupation_ ?'}) (Confidence: 1.00, Lift: 17.67, Interest: 17.67)
Rule 8: If frozenset({'workclass_ ?'}) then frozenset({'education-num', 'occupation_ ?'}) (Confidence: 1.00, Lift: 17.67, Interest: 17.67)
Rule 9: If frozenset({'workclass_ ?', 'hours-per-week'}) then frozenset({'occupation_ ?'}) (Confidence: 1.00, Lift: 17.67, Interest: 17.67)
Rule 10: If frozenset({'workclass_ ?'}) then frozenset({'hours-per-week', 'occupation_ ?'}) (Confidence: 1.00, Lift: 17.67, Interest: 17.67)
Rules for min_support=0.05 and min_interest=0.70:
Rule 1: If frozenset({'workclass_ ?'}) then frozenset({'occupation_ ?'}) (Confidence: 1.00, Lift: 17.67, Interest: 17.67)
Rule 2: If frozenset({'workclass_ ?', 'native-country_ United-States'}) then frozenset({'occupation_ ?'}) (Confidence: 1.00, Lift: 17.67, Interest: 17.67)
Rule 3: If frozenset({'workclass_ ?', 'age'}) then frozenset({'occupation_ ?'}) (Confidence: 1.00, Lift: 17.67, Interest: 17.67)
Rule 4: If frozenset({'workclass_ ?'}) then frozenset({'age', 'occupation_ ?'}) (Confidence: 1.00, Lift: 17.67, Interest: 17.67)
Rule 5: If frozenset({'workclass_ ?', 'fnlwgt'}) then frozenset({'occupation_ ?'}) (Confidence: 1.00, Lift: 17.67, Interest: 17.67)
Rule 6: If frozenset({'workclass_ ?'}) then frozenset({'occupation_ ?', 'fnlwgt'}) (Confidence: 1.00, Lift: 17.67, Interest: 17.67)
Rule 7: If frozenset({'workclass_ ?', 'education-num'}) then frozenset({'occupation_ ?'}) (Confidence: 1.00, Lift: 17.67, Interest: 17.67)
Rule 8: If frozenset({'workclass_ ?'}) then frozenset({'education-num', 'occupation_ ?'}) (Confidence: 1.00, Lift: 17.67, Interest: 17.67)
Rule 9: If frozenset({'workclass_ ?', 'hours-per-week'}) then frozenset({'occupation_ ?'}) (Confidence: 1.00, Lift: 17.67, Interest: 17.67)
Rule 10: If frozenset({'workclass_ ?'}) then frozenset({'hours-per-week', 'occupation_ ?'}) (Confidence: 1.00, Lift: 17.67, Interest: 17.67)
Rules for min_support=0.05 and min_interest=0.90:
Rule 1: If frozenset({'workclass_ ?'}) then frozenset({'occupation_ ?'}) (Confidence: 1.00, Lift: 17.67, Interest: 17.67)
Rule 2: If frozenset({'workclass_ ?', 'native-country_ United-States'}) then frozenset({'occupation_ ?'}) (Confidence: 1.00, Lift: 17.67, Interest: 17.67)
Rule 3: If frozenset({'workclass_ ?', 'age'}) then frozenset({'occupation_ ?'}) (Confidence: 1.00, Lift: 17.67, Interest: 17.67)
Rule 4: If frozenset({'workclass_ ?'}) then frozenset({'age', 'occupation_ ?'}) (Confidence: 1.00, Lift: 17.67, Interest: 17.67)
Rule 5: If frozenset({'workclass_ ?', 'fnlwgt'}) then frozenset({'occupation_ ?'}) (Confidence: 1.00, Lift: 17.67, Interest: 17.67)
Rule 6: If frozenset({'workclass_ ?'}) then frozenset({'occupation_ ?', 'fnlwgt'}) (Confidence: 1.00, Lift: 17.67, Interest: 17.67)
Rule 7: If frozenset({'workclass_ ?', 'education-num'}) then frozenset({'occupation_ ?'}) (Confidence: 1.00, Lift: 17.67, Interest: 17.67)
Rule 8: If frozenset({'workclass_ ?'}) then frozenset({'education-num', 'occupation_ ?'}) (Confidence: 1.00, Lift: 17.67, Interest: 17.67)
Rule 9: If frozenset({'workclass_ ?', 'hours-per-week'}) then frozenset({'occupation_ ?'}) (Confidence: 1.00, Lift: 17.67, Interest: 17.67)
Rule 10: If frozenset({'workclass_ ?'}) then frozenset({'hours-per-week', 'occupation_ ?'}) (Confidence: 1.00, Lift: 17.67, Interest: 17.67)

/usr/local/lib/python3.10/dist-packages/mlxtend/frequent_patterns/fpcommon.py:110: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

Rules for min_support=0.10 and min_interest=0.50:
Rule 1: If frozenset({'education_ HS-grad', 'race_ White', 'relationship_ Husband'}) then frozenset({'native-country_ United-States', 'marital-status_ Married-civ-spouse', 'sex_ Male'}) (Confidence: 0.95, Lift: 2.59, Interest: 2.46)
Rule 2: If frozenset({'education_ HS-grad', 'race_ White', 'age', 'relationship_ Husband'}) then frozenset({'native-country_ United-States', 'marital-status_ Married-civ-spouse', 'sex_ Male'}) (Confidence: 0.95, Lift: 2.59, Interest: 2.46)
Rule 3: If frozenset({'education_ HS-grad', 'race_ White', 'relationship_ Husband'}) then frozenset({'native-country_ United-States', 'marital-status_ Married-civ-spouse', 'age', 'sex_ Male'}) (Confidence: 0.95, Lift: 2.59, Interest: 2.46)
Rule 4: If frozenset({'education_ HS-grad', 'race_ White', 'relationship_ Husband', 'fnlwgt'}) then frozenset({'native-country_ United-States', 'marital-status_ Married-civ-spouse', 'sex_ Male'}) (Confidence: 0.95, Lift: 2.59, Interest: 2.46)
Rule 5: If frozenset({'education_ HS-grad', 'race_ White', 'relationship_ Husband'}) then frozenset({'native-country_ United-States', 'marital-status_ Married-civ-spouse', 'sex_ Male', 'fnlwgt'}) (Confidence: 0.95, Lift: 2.59, Interest: 2.46)
Rule 6: If frozenset({'education_ HS-grad', 'race_ White', 'education-num', 'relationship_ Husband'}) then frozenset({'native-country_ United-States', 'marital-status_ Married-civ-spouse', 'sex_ Male'}) (Confidence: 0.95, Lift: 2.59, Interest: 2.46)
Rule 7: If frozenset({'education_ HS-grad', 'race_ White', 'relationship_ Husband'}) then frozenset({'native-country_ United-States', 'marital-status_ Married-civ-spouse', 'education-num', 'sex_ Male'}) (Confidence: 0.95, Lift: 2.59, Interest: 2.46)
Rule 8: If frozenset({'education_ HS-grad', 'race_ White', 'hours-per-week', 'relationship_ Husband'}) then frozenset({'native-country_ United-States', 'marital-status_ Married-civ-spouse', 'sex_ Male'}) (Confidence: 0.95, Lift: 2.59, Interest: 2.46)
Rule 9: If frozenset({'education_ HS-grad', 'race_ White', 'relationship_ Husband'}) then frozenset({'native-country_ United-States', 'marital-status_ Married-civ-spouse', 'hours-per-week', 'sex_ Male'}) (Confidence: 0.95, Lift: 2.59, Interest: 2.46)
Rule 10: If frozenset({'relationship_ Husband', 'fnlwgt', 'education_ HS-grad', 'race_ White', 'age'}) then frozenset({'native-country_ United-States', 'marital-status_ Married-civ-spouse', 'sex_ Male'}) (Confidence: 0.95, Lift: 2.59, Interest: 2.46)
Rules for min_support=0.10 and min_interest=0.70:
Rule 1: If frozenset({'education_ HS-grad', 'race_ White', 'relationship_ Husband'}) then frozenset({'native-country_ United-States', 'marital-status_ Married-civ-spouse', 'sex_ Male'}) (Confidence: 0.95, Lift: 2.59, Interest: 2.46)
Rule 2: If frozenset({'education_ HS-grad', 'race_ White', 'age', 'relationship_ Husband'}) then frozenset({'native-country_ United-States', 'marital-status_ Married-civ-spouse', 'sex_ Male'}) (Confidence: 0.95, Lift: 2.59, Interest: 2.46)
Rule 3: If frozenset({'education_ HS-grad', 'race_ White', 'relationship_ Husband'}) then frozenset({'native-country_ United-States', 'marital-status_ Married-civ-spouse', 'age', 'sex_ Male'}) (Confidence: 0.95, Lift: 2.59, Interest: 2.46)
Rule 4: If frozenset({'education_ HS-grad', 'race_ White', 'relationship_ Husband', 'fnlwgt'}) then frozenset({'native-country_ United-States', 'marital-status_ Married-civ-spouse', 'sex_ Male'}) (Confidence: 0.95, Lift: 2.59, Interest: 2.46)
Rule 5: If frozenset({'education_ HS-grad', 'race_ White', 'relationship_ Husband'}) then frozenset({'native-country_ United-States', 'marital-status_ Married-civ-spouse', 'sex_ Male', 'fnlwgt'}) (Confidence: 0.95, Lift: 2.59, Interest: 2.46)
Rule 6: If frozenset({'education_ HS-grad', 'race_ White', 'education-num', 'relationship_ Husband'}) then frozenset({'native-country_ United-States', 'marital-status_ Married-civ-spouse', 'sex_ Male'}) (Confidence: 0.95, Lift: 2.59, Interest: 2.46)
Rule 7: If frozenset({'education_ HS-grad', 'race_ White', 'relationship_ Husband'}) then frozenset({'native-country_ United-States', 'marital-status_ Married-civ-spouse', 'education-num', 'sex_ Male'}) (Confidence: 0.95, Lift: 2.59, Interest: 2.46)
Rule 8: If frozenset({'education_ HS-grad', 'race_ White', 'hours-per-week', 'relationship_ Husband'}) then frozenset({'native-country_ United-States', 'marital-status_ Married-civ-spouse', 'sex_ Male'}) (Confidence: 0.95, Lift: 2.59, Interest: 2.46)
Rule 9: If frozenset({'education_ HS-grad', 'race_ White', 'relationship_ Husband'}) then frozenset({'native-country_ United-States', 'marital-status_ Married-civ-spouse', 'hours-per-week', 'sex_ Male'}) (Confidence: 0.95, Lift: 2.59, Interest: 2.46)
Rule 10: If frozenset({'relationship_ Husband', 'fnlwgt', 'education_ HS-grad', 'race_ White', 'age'}) then frozenset({'native-country_ United-States', 'marital-status_ Married-civ-spouse', 'sex_ Male'}) (Confidence: 0.95, Lift: 2.59, Interest: 2.46)
Rules for min_support=0.10 and min_interest=0.90:
Rule 1: If frozenset({'education_ HS-grad', 'race_ White', 'relationship_ Husband'}) then frozenset({'native-country_ United-States', 'marital-status_ Married-civ-spouse', 'sex_ Male'}) (Confidence: 0.95, Lift: 2.59, Interest: 2.46)
Rule 2: If frozenset({'education_ HS-grad', 'race_ White', 'age', 'relationship_ Husband'}) then frozenset({'native-country_ United-States', 'marital-status_ Married-civ-spouse', 'sex_ Male'}) (Confidence: 0.95, Lift: 2.59, Interest: 2.46)
Rule 3: If frozenset({'education_ HS-grad', 'race_ White', 'relationship_ Husband'}) then frozenset({'native-country_ United-States', 'marital-status_ Married-civ-spouse', 'age', 'sex_ Male'}) (Confidence: 0.95, Lift: 2.59, Interest: 2.46)
Rule 4: If frozenset({'education_ HS-grad', 'race_ White', 'relationship_ Husband', 'fnlwgt'}) then frozenset({'native-country_ United-States', 'marital-status_ Married-civ-spouse', 'sex_ Male'}) (Confidence: 0.95, Lift: 2.59, Interest: 2.46)
Rule 5: If frozenset({'education_ HS-grad', 'race_ White', 'relationship_ Husband'}) then frozenset({'native-country_ United-States', 'marital-status_ Married-civ-spouse', 'sex_ Male', 'fnlwgt'}) (Confidence: 0.95, Lift: 2.59, Interest: 2.46)
Rule 6: If frozenset({'education_ HS-grad', 'race_ White', 'education-num', 'relationship_ Husband'}) then frozenset({'native-country_ United-States', 'marital-status_ Married-civ-spouse', 'sex_ Male'}) (Confidence: 0.95, Lift: 2.59, Interest: 2.46)
Rule 7: If frozenset({'education_ HS-grad', 'race_ White', 'relationship_ Husband'}) then frozenset({'native-country_ United-States', 'marital-status_ Married-civ-spouse', 'education-num', 'sex_ Male'}) (Confidence: 0.95, Lift: 2.59, Interest: 2.46)
Rule 8: If frozenset({'education_ HS-grad', 'race_ White', 'hours-per-week', 'relationship_ Husband'}) then frozenset({'native-country_ United-States', 'marital-status_ Married-civ-spouse', 'sex_ Male'}) (Confidence: 0.95, Lift: 2.59, Interest: 2.46)
Rule 9: If frozenset({'education_ HS-grad', 'race_ White', 'relationship_ Husband'}) then frozenset({'native-country_ United-States', 'marital-status_ Married-civ-spouse', 'hours-per-week', 'sex_ Male'}) (Confidence: 0.95, Lift: 2.59, Interest: 2.46)
Rule 10: If frozenset({'relationship_ Husband', 'fnlwgt', 'education_ HS-grad', 'race_ White', 'age'}) then frozenset({'native-country_ United-States', 'marital-status_ Married-civ-spouse', 'sex_ Male'}) (Confidence: 0.95, Lift: 2.59, Interest: 2.46)

/usr/local/lib/python3.10/dist-packages/mlxtend/frequent_patterns/fpcommon.py:110: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

Rules for min_support=0.15 and min_interest=0.50:
Rule 1: If frozenset({'relationship_ Husband'}) then frozenset({'marital-status_ Married-civ-spouse', 'sex_ Male'}) (Confidence: 1.00, Lift: 2.44, Interest: 2.44)
Rule 2: If frozenset({'age', 'relationship_ Husband'}) then frozenset({'marital-status_ Married-civ-spouse', 'sex_ Male'}) (Confidence: 1.00, Lift: 2.44, Interest: 2.44)
Rule 3: If frozenset({'relationship_ Husband'}) then frozenset({'marital-status_ Married-civ-spouse', 'age', 'sex_ Male'}) (Confidence: 1.00, Lift: 2.44, Interest: 2.44)
Rule 4: If frozenset({'relationship_ Husband', 'fnlwgt'}) then frozenset({'marital-status_ Married-civ-spouse', 'sex_ Male'}) (Confidence: 1.00, Lift: 2.44, Interest: 2.44)
Rule 5: If frozenset({'relationship_ Husband'}) then frozenset({'marital-status_ Married-civ-spouse', 'sex_ Male', 'fnlwgt'}) (Confidence: 1.00, Lift: 2.44, Interest: 2.44)
Rule 6: If frozenset({'education-num', 'relationship_ Husband'}) then frozenset({'marital-status_ Married-civ-spouse', 'sex_ Male'}) (Confidence: 1.00, Lift: 2.44, Interest: 2.44)
Rule 7: If frozenset({'relationship_ Husband'}) then frozenset({'marital-status_ Married-civ-spouse', 'education-num', 'sex_ Male'}) (Confidence: 1.00, Lift: 2.44, Interest: 2.44)
Rule 8: If frozenset({'hours-per-week', 'relationship_ Husband'}) then frozenset({'marital-status_ Married-civ-spouse', 'sex_ Male'}) (Confidence: 1.00, Lift: 2.44, Interest: 2.44)
Rule 9: If frozenset({'relationship_ Husband'}) then frozenset({'marital-status_ Married-civ-spouse', 'hours-per-week', 'sex_ Male'}) (Confidence: 1.00, Lift: 2.44, Interest: 2.44)
Rule 10: If frozenset({'age', 'relationship_ Husband', 'fnlwgt'}) then frozenset({'marital-status_ Married-civ-spouse', 'sex_ Male'}) (Confidence: 1.00, Lift: 2.44, Interest: 2.44)
Rules for min_support=0.15 and min_interest=0.70:
Rule 1: If frozenset({'relationship_ Husband'}) then frozenset({'marital-status_ Married-civ-spouse', 'sex_ Male'}) (Confidence: 1.00, Lift: 2.44, Interest: 2.44)
Rule 2: If frozenset({'age', 'relationship_ Husband'}) then frozenset({'marital-status_ Married-civ-spouse', 'sex_ Male'}) (Confidence: 1.00, Lift: 2.44, Interest: 2.44)
Rule 3: If frozenset({'relationship_ Husband'}) then frozenset({'marital-status_ Married-civ-spouse', 'age', 'sex_ Male'}) (Confidence: 1.00, Lift: 2.44, Interest: 2.44)
Rule 4: If frozenset({'relationship_ Husband', 'fnlwgt'}) then frozenset({'marital-status_ Married-civ-spouse', 'sex_ Male'}) (Confidence: 1.00, Lift: 2.44, Interest: 2.44)
Rule 5: If frozenset({'relationship_ Husband'}) then frozenset({'marital-status_ Married-civ-spouse', 'sex_ Male', 'fnlwgt'}) (Confidence: 1.00, Lift: 2.44, Interest: 2.44)
Rule 6: If frozenset({'education-num', 'relationship_ Husband'}) then frozenset({'marital-status_ Married-civ-spouse', 'sex_ Male'}) (Confidence: 1.00, Lift: 2.44, Interest: 2.44)
Rule 7: If frozenset({'relationship_ Husband'}) then frozenset({'marital-status_ Married-civ-spouse', 'education-num', 'sex_ Male'}) (Confidence: 1.00, Lift: 2.44, Interest: 2.44)
Rule 8: If frozenset({'hours-per-week', 'relationship_ Husband'}) then frozenset({'marital-status_ Married-civ-spouse', 'sex_ Male'}) (Confidence: 1.00, Lift: 2.44, Interest: 2.44)
Rule 9: If frozenset({'relationship_ Husband'}) then frozenset({'marital-status_ Married-civ-spouse', 'hours-per-week', 'sex_ Male'}) (Confidence: 1.00, Lift: 2.44, Interest: 2.44)
Rule 10: If frozenset({'age', 'relationship_ Husband', 'fnlwgt'}) then frozenset({'marital-status_ Married-civ-spouse', 'sex_ Male'}) (Confidence: 1.00, Lift: 2.44, Interest: 2.44)
Rules for min_support=0.15 and min_interest=0.90:
Rule 1: If frozenset({'relationship_ Husband'}) then frozenset({'marital-status_ Married-civ-spouse', 'sex_ Male'}) (Confidence: 1.00, Lift: 2.44, Interest: 2.44)
Rule 2: If frozenset({'age', 'relationship_ Husband'}) then frozenset({'marital-status_ Married-civ-spouse', 'sex_ Male'}) (Confidence: 1.00, Lift: 2.44, Interest: 2.44)
Rule 3: If frozenset({'relationship_ Husband'}) then frozenset({'marital-status_ Married-civ-spouse', 'age', 'sex_ Male'}) (Confidence: 1.00, Lift: 2.44, Interest: 2.44)
Rule 4: If frozenset({'relationship_ Husband', 'fnlwgt'}) then frozenset({'marital-status_ Married-civ-spouse', 'sex_ Male'}) (Confidence: 1.00, Lift: 2.44, Interest: 2.44)
Rule 5: If frozenset({'relationship_ Husband'}) then frozenset({'marital-status_ Married-civ-spouse', 'sex_ Male', 'fnlwgt'}) (Confidence: 1.00, Lift: 2.44, Interest: 2.44)
Rule 6: If frozenset({'education-num', 'relationship_ Husband'}) then frozenset({'marital-status_ Married-civ-spouse', 'sex_ Male'}) (Confidence: 1.00, Lift: 2.44, Interest: 2.44)
Rule 7: If frozenset({'relationship_ Husband'}) then frozenset({'marital-status_ Married-civ-spouse', 'education-num', 'sex_ Male'}) (Confidence: 1.00, Lift: 2.44, Interest: 2.44)
Rule 8: If frozenset({'hours-per-week', 'relationship_ Husband'}) then frozenset({'marital-status_ Married-civ-spouse', 'sex_ Male'}) (Confidence: 1.00, Lift: 2.44, Interest: 2.44)
Rule 9: If frozenset({'relationship_ Husband'}) then frozenset({'marital-status_ Married-civ-spouse', 'hours-per-week', 'sex_ Male'}) (Confidence: 1.00, Lift: 2.44, Interest: 2.44)
Rule 10: If frozenset({'age', 'relationship_ Husband', 'fnlwgt'}) then frozenset({'marital-status_ Married-civ-spouse', 'sex_ Male'}) (Confidence: 1.00, Lift: 2.44, Interest: 2.44)